use_frameworks!

platform :ios, '10.0'

target 'FirstCocoapodsLibrary_Example' do
  pod 'FirstCocoapodsLibrary', :path => '../'

  target 'FirstCocoapodsLibrary_Tests' do
    inherit! :search_paths

    
  end
end
